"""initial schema

Revision ID: a3d6b8422ed4
Revises: 
Create Date: 2026-01-31 13:49:29.724018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d6b8422ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lemonsqueezy_subscription_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lemonsqueezy_subscription_id')
        batch_op.drop_column('subscription_expires_at')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
